version: '3'

services:
  app:
    build: . # le build va chercher le Dockerfile du dossier .
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    volumes: # Les volumes permettent de stocker les données et les persister !
      - app_static:/app/static
  
  database:
    image: postgres:latest
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  webserver: # Passer par un serveur web permet de gérer les fichiers statics (styles, etc...), faciliter la sécurité (HTTPS) et les certificats, etc...
  # Le webserver s'occupe des requêtes HTTP
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - app_static:/var/www/static
    ports:
      - "8080:8081"
    depends_on:
      - app

volumes:
  app_static:
  database_data: