name: Build Django App

on: ## déclencheurs
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: blog-django-mns
  TAR_NAME: blog-django-mns.tar

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Save Docker image
        run: docker save $IMAGE_NAME:latest -o $TAR_NAME
